### ISSUE TITLE
Installer fails on MacOsX

### ISSUE THREAD

**Issue by shakty** [nodeGame/nodegame#25]
It looks like a different directory structure is followed

```
Oops! The following error/s occurred: 
{ Error: ENOENT: no such file or directory, mkdir '/Users/XXX/node_modules/nodegame/log'

    at Object.mkdirSync (fs.js:753:3)

    at someMagic (/Users/XXX/nodegame-installer.js:397:12)

    at execFile (/Users/XXX/nodegame-installer.js:257:21)

    at ChildProcess.exithandler (child_process.js:285:7)

    at ChildProcess.emit (events.js:189:13)

    at maybeClose (internal/child_process.js:970:16)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

  errno: -2,

  syscall: 'mkdir',

  code: 'ENOENT',

  path:

   '/Users/XXXl/node_modules/nodegame/log' }

  Installation did not complete successfully.
```

**Comment by shakty** [comment]
This just happens on some Mac. Under investigation

**Comment by shakty** [comment]
This happens if there is another node_modules folder in a parent directory. Fixed.
